services:
  portfolio:
    image: nginx:alpine
    container_name: portfolio
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=alangarciia.duckdns.org
      - LETSENCRYPT_HOST=alangarciia.duckdns.org
      - LETSENCRYPT_EMAIL=alan.g.perez006@gmail.com
    networks:
      - prova_competencial_network

networks:
  prova_competencial_network:
    external: true